repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        args: ["--fix"]          # auto-fix safe lint issues (e.g., import sort)
      - id: ruff-format          # formatter (replaces Black)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies: [types-PyYAML, pydantic, fastapi, typer]
        args: [--config-file, pyproject.toml]
        exclude: ^services/api/
